# NumPy: Numerical Python

### Karl N. Kirschner

Numpy is the foundation for
- Pandas
- Matplotlib
- Scikit-learn


- Excels at large **arrays** of data


- Array: an n-dimensional array (i.e. ndarray):
    - a collections of values that have 1 or more dimensions
    - 1D array --> vector
    - nD array --> matrix


- All array data must be the same (i.e. homogeneous)


- Can perform computations on entire arrays without the need of loops


- Does not come by default with Python - must be installed


https://numpy.org/doc/stable/
---

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import time

#%matplotlib inline

## N-dimensional array object (i.e. ndarray)

Let's create two objects:
1. numpy array (via Array RANGE: https://numpy.org/doc/stable/reference/generated/numpy.arange.html), and
2. a regular list

Then we can find demonstrate which is faster using the time library.

In [8]:
my_array = np.arange(100000)
my_array

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [9]:
my_list = list(range(100000))
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [23]:
initial_time = time.time()

## multiply my_array by 2, and that 100 times
for x in range(100):
    my_array_2 = my_array*2

print("Time: {0:.2e} milliseconds ---".format( (time.time() - initial_time)/1000))

Time: 1.39e-05 milliseconds ---


In [24]:
initial_time = time.time()

for x in range(100):
    my_list_2 = my_list*2

print("Time: {0:.2e} milliseconds ---".format( (time.time() - initial_time)/1000))

Time: 1.70e-04 milliseconds ---


---
## General information

In [30]:
## Two data lists with 5 data points
data_1 = [6, 1, 6, 7, 9]
data_2 = [3, 5, 4, 2, 8]

In [31]:
data_1

[6, 1, 6, 7, 9]

In [32]:
data_2

[3, 5, 4, 2, 8]

In [33]:
## Two different arrays, each with a shape of (1,5)
array_1 = np.array(data_1)
array_2 = np.array(data_2)

In [34]:
array_1

array([6, 1, 6, 7, 9])

In [35]:
array_2

array([3, 5, 4, 2, 8])

In [36]:
## A nested list, with each sublist contains 5 data points
data_3 = [[-6, 1, 6, 7, 9], [-5, 0, 2, 4, 3]]

## One array, with a shape of (2,5)
array_3 = np.array(data_3)

array_3

array([[-6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3]])

Put array_3 to memory - we will use it a lot later on  in the lecture.

#### Array shapes and dimensions

In [44]:
## 1D shape
array_1.shape

(5,)

In [50]:
## Note, this would change if you added double brackets above
##     data_1 = [[6, 1, 6, 7, 9]]
##     array_1 = np.array(data_1)
example = [[6, 1, 6, 7, 9]]
test = np.array(example)
test.shape

(1, 5)

In [51]:
## nD shape
array_3.shape

(2, 5)

In [52]:
array_3.ndim

2

Reminder of using type to figure out what you are dealing with.

In [55]:
type(array_3)

numpy.ndarray

#### Data types

- https://numpy.org/doc/stable/reference/arrays.dtypes.html
- https://numpy.org/doc/stable/reference/generated/numpy.dtype.html?highlight=dtype#numpy.dtype

In [56]:
array_3.dtype

dtype('int64')

---
## More on creating new arrays

Create an array with a shape of (3,5),and fill it with ca. pi

In [57]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

Create an array with a shape of (1,30) from -10 to 50 using a stepping size of 2

In [58]:
np.arange(-10, 50, 2)

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10,  12,  14,
        16,  18,  20,  22,  24,  26,  28,  30,  32,  34,  36,  38,  40,
        42,  44,  46,  48])

Create an array that contains 10 evenely spaced values between -1 and 1
- numpy's linspace: https://numpy.org/devdocs/reference/generated/numpy.linspace.html

In [59]:
np.linspace(-1, 1, 10)

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

Create array with random, but continuous distributed, values between 0 and 1
- random.random_sample function: https://numpy.org/doc/stable/reference/random/generated/numpy.random.random_sample.html#numpy.random.random_sample

In [66]:
np.random.random_sample(3)

array([0.69750387, 0.88009562, 0.91513179])

In [69]:
## shape of (3,4)
np.random.random_sample((3, 4))

array([[0.42512333, 0.98629153, 0.01794282, 0.20013074],
       [0.06346523, 0.80492876, 0.89235775, 0.25962562],
       [0.6263044 , 0.39873283, 0.3554029 , 0.32265974]])

---
## Accessing arrays

In [74]:
## 1D array (i.e. (1,5) from above)
array_1

array([6, 1, 6, 7, 9])

In [75]:
## accessing the fourth item position (i.e. index of 3)
array_1[3]

7

In [76]:
## 2D array (i.e. (2,5) from above)
array_3

array([[-6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3]])

In [78]:
## access the second sublist from the 2D array
array_3[1]

array([-5,  0,  2,  4,  3])

In [86]:
## access the first sublist and the fourth item position
array_3[0,4]

9

Slicing - demo using [0:1], [1:2], [0:2] and [0:3]

In [91]:
array_3[0:1]

array([[-6,  1,  6,  7,  9]])

In [92]:
array_3[1:2]

array([[-5,  0,  2,  4,  3]])

In [93]:
array_3[0:2]

array([[-6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3]])

In [94]:
array_3[0:3]

array([[-6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3]])

---
## Joining arrays

In [95]:
array_1

array([6, 1, 6, 7, 9])

In [96]:
array_2

array([3, 5, 4, 2, 8])

**Concatenate**: https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

Multiple 1D arrays

In [111]:
np.concatenate([array_1, array_2, array_1])

array([6, 1, 6, 7, 9, 3, 5, 4, 2, 8, 6, 1, 6, 7, 9])

In [112]:
array_3

array([[-6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3]])

Multiple nD arrays, along their first axis (i.e. axis=0) - conceptually, this like adding items to columns in a table

(or as an altertive perspective - adding additional rows)

In [134]:
array_big = np.concatenate([array_3, array_3, array_3], axis=0)
array_big

array([[-6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3],
       [-6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3],
       [-6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3]])

In [135]:
array_big.shape

(6, 5)

In [136]:
## Use Pandas to print out the table in a more human (i.e. a scientist) readable form
print(pd.DataFrame(array_big))

   0  1  2  3  4
0 -6  1  6  7  9
1 -5  0  2  4  3
2 -6  1  6  7  9
3 -5  0  2  4  3
4 -6  1  6  7  9
5 -5  0  2  4  3


Multiple nD arrays, along their second axis (i.e. axis=1) - conceptually, this like adding items to rows in a table

In [142]:
## Use Pandas
print(pd.DataFrame(array_3))

   0  1  2  3  4
0 -6  1  6  7  9
1 -5  0  2  4  3


In [143]:
## Multiple nD arrays, along their second axis
array_long = np.concatenate([array_3, array_3, array_3], axis=1)
array_long

array([[-6,  1,  6,  7,  9, -6,  1,  6,  7,  9, -6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3, -5,  0,  2,  4,  3, -5,  0,  2,  4,  3]])

In [144]:
array_long.shape

(2, 15)

In [145]:
## Use Pandas
print(pd.DataFrame(array_long))

   0  1  2  3  4  5  6  7  8  9  10  11  12  13  14
0 -6  1  6  7  9 -6  1  6  7  9  -6   1   6   7   9
1 -5  0  2  4  3 -5  0  2  4  3  -5   0   2   4   3


#### Multiple mixed dimensional arrays
- must pay attention to the dimensions


- vertical stacked
- horizontal stacked

Vertical stacked
- nD arrays must be (x,N) and (y,N) where N is the same value

In [160]:
print(array_3)
print()
print(array_3.shape)

[[-6  1  6  7  9]
 [-5  0  2  4  3]]

(2, 5)


In [162]:
print(array_big)
print()
print(array_big.shape)

[[-6  1  6  7  9]
 [-5  0  2  4  3]
 [-6  1  6  7  9]
 [-5  0  2  4  3]
 [-6  1  6  7  9]
 [-5  0  2  4  3]]

(6, 5)


In [173]:
array_vstack = np.vstack([array_3, array_big])
array_vstack

array([[-6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3],
       [-6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3],
       [-6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3],
       [-6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3]])

In [174]:
array_vstack.shape

(8, 5)

Now interestingly (and logically), we can also do this with our array_1 (i.e. (5,) ) that we created above

In [182]:
## review what we have for array_3
print(array_1)
print()
print(array_1.shape)

[6 1 6 7 9]

(5,)


In [183]:
array_vstack = np.vstack([array_1, array_3])
array_vstack

array([[ 6,  1,  6,  7,  9],
       [-6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3]])

In [184]:
array_vstack.shape

(3, 5)

Now, let's show when it doesn't work:

In [185]:
## example of when the arrays have different N values
array_4 = np.array([['99', 99, 99, 99]])
print(array_4)
print()
print(array_4.shape)

[['99' '99' '99' '99']]

(1, 4)


In [186]:
np.vstack([array_4, array_3])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 5

Horizontal Stacked
- nD arrays must be (N,x) and (N,y) where N is the same value

Using our examples, we need a new array that has (2,x) values since array_3 is (2,y)

In [195]:
array_4 = np.array([[99], [99]])
print(array_4)
print()
print(array_4.shape)

[[99]
 [99]]

(2, 1)


In [196]:
array_hstack = np.hstack([array_4, array_3])
array_hstack

array([[99, -6,  1,  6,  7,  9],
       [99, -5,  0,  2,  4,  3]])

In [197]:
array_hstack.shape

(2, 6)

Now, let's show when it doesn't work:

In [198]:
array_big.shape

(6, 5)

In [199]:
array_hstack = np.hstack([array_4, array_big])
array_hstack

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 6

---
## Math with ndarrays
- np.add and np.subtract
- np.multiple and np.divide
- np.power
- np.negative (multiplies x by -1)

In [200]:
array_3

array([[-6,  1,  6,  7,  9],
       [-5,  0,  2,  4,  3]])

In [201]:
## Method 1 (numpy function)
np.add(array_3, 5)

array([[-1,  6, 11, 12, 14],
       [ 0,  5,  7,  9,  8]])

In [202]:
## Method 2 (python built-in function)
array_3 + 5

array([[-1,  6, 11, 12, 14],
       [ 0,  5,  7,  9,  8]])

Note
- Using numpy vs built-in functions doesn't really matter here since you are performing the action on a numpy array

### Math between arrays
- math operations between equal sized arrays is done via element-wise

In [203]:
## add and subtract
array_3 + array_3

array([[-12,   2,  12,  14,  18],
       [-10,   0,   4,   8,   6]])

In [204]:
array_3 - array_3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [205]:
## multiplication
array_3 * array_3

array([[36,  1, 36, 49, 81],
       [25,  0,  4, 16,  9]])

In [206]:
data_4 = [[-1, -1, -1, -1, -1], [-1, -1, -1, -1, -1]]
array_4 = np.array(data_4)

In [207]:
array_3 * array_4

array([[ 6, -1, -6, -7, -9],
       [ 5,  0, -2, -4, -3]])

In [208]:
## division
1/array_3

<ipython-input-208-ec9f4b08d471>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/array_3


array([[-0.16666667,  1.        ,  0.16666667,  0.14285714,  0.11111111],
       [-0.2       ,         inf,  0.5       ,  0.25      ,  0.33333333]])

In [209]:
## powers
array_3**3

array([[-216,    1,  216,  343,  729],
       [-125,    0,    8,   64,   27]])

### Absolute values

In [212]:
## Python3 built-in function
abs(array_3)

array([[6, 1, 6, 7, 9],
       [5, 0, 2, 4, 3]])

In [213]:
np.absolute(array_3)

array([[6, 1, 6, 7, 9],
       [5, 0, 2, 4, 3]])

### Booleans

In [214]:
print(array_3 == -6)

[[ True False False False False]
 [False False False False False]]


### Trigonometric
- np.sin()
- np.cos()
- np.arcsin()
- etc.

In [215]:
## trig on a single input value
np.sin(-6)

0.27941549819892586

In [216]:
## trig on an numpy array
np.sin(array_3)

array([[ 0.2794155 ,  0.84147098, -0.2794155 ,  0.6569866 ,  0.41211849],
       [ 0.95892427,  0.        ,  0.90929743, -0.7568025 ,  0.14112001]])

### Exponents and logarithms

In [226]:
## Note that the resulting lists aren't seperated by a comma
##    (as seen above) due to the print statement
x = np.array([2, 3])
print("x     =", x)
print("2^x   =", np.exp2(x))
print("10^x   =", np.power(10, x))
print("e^x   =", np.exp(x))

x     = [2 3]
2^x   = [4. 8.]
10^x   = [ 100 1000]
e^x   = [ 7.3890561  20.08553692]


In [227]:
x = [4., 8.]
print("log2(x)  =", np.log2(x))

x = [100., 1000.]
print("log10(x) =", np.log10(x))

x = [7.3890561, 20.08553692]
print("ln(x)    =", np.log(x))

log2(x)  = [2. 3.]
log10(x) = [2. 3.]
ln(x)    = [2. 3.]


---
### A more complex example

In [228]:
## Celcius to Fahrenheit
## Average temperature in Bonn (January ---> December)
data_celcius = [2.0, 2.8, 5.7, 9.3, 13.3, 16.5, 18.1, 17.6, 14.9, 10.5, 6.1, 3.2]
array_celcius = np.array(data_celcius)
array_celcius

array([ 2. ,  2.8,  5.7,  9.3, 13.3, 16.5, 18.1, 17.6, 14.9, 10.5,  6.1,
        3.2])

In [229]:
array_fahrenheit = array_celcius*(9/5) + 32

In [230]:
plt.plot(array_celcius)
plt.plot(array_fahrenheit)
plt.show()

---
## Numpy statistics

#### Side note: numpy's random number generators
- generators (e.g. normal/gaussian, geometric, bionomial) https://numpy.org/doc/1.18/reference/random/generator.html


Example:
What is the random distribution of 10 attempts that have a success propobility of 60%, where the distribution itself is governed by a geometric distribution?


In [231]:
## a 1 means success
s = np.random.geometric(0.60, size=10)
s

array([2, 1, 1, 1, 4, 3, 1, 4, 1, 1])

Filling a numpy array with random numbers
- Create an array (3,3) of Gaussian distributed random values: mean=0.0 and standard deviation=0.1

In [ ]:
random_data = np.random.normal(0, 0.1, (3, 3))
random_data

In [ ]:
plt.plot(random_data)
plt.show()

In [ ]:
import statistics
x = [4.20301882, 6.01710072, 5.34706913, 4.8524383, 6.00683874, 4.61264656, 2.58228863, 4.78684698, 4.80212896]
statistics.median(x)

In [ ]:
np.mean(random_data)

In [ ]:
np.median(random_data)

---
## Standard deviation and variance

In [ ]:
data = [1, 2, 4, 5, 8]

#### variance
- Libreoffice spreadsheet give a variance of '=VAR(1,2,4,5,8)' of 7.5
- I beleive Matlab also gives 7.5

Using the statistics's library

In [ ]:
statistics.variance(data)

These are actually the 'sample variance.'

However, if you use NumPy by simply typing:

In [ ]:
np.var(data)

In this case there is a hidden variable called ddof ("Delta Degrees of Freedom")
    - the denomenator is divided by 'N -ddof'

ddof = 1 gives you a population variance

In [ ]:
## population variance
np.var(data, ddof=0)

In [ ]:
## sample variance (always larger than the population variance)
np.var(data, ddof=1)

https://numpy.org/doc/1.18/reference/generated/numpy.var.html?highlight=variance

- sample: "ddof=1 provides an unbiased estimator of the variance of a hypothetical infinite population"
- population: "ddof=0 provides a maximum likelihood estimate of the variance for normally distributed variables"

The same is true for standard deviation.

In [ ]:
## standard deviation
## libreoffice gives '=stdev(1,2,4,5,8)' of 2.7386127875

statistics.stdev(data)

In [ ]:
## sample standard deviation
np.std(data, ddof=1)

In [ ]:
## population standard deviation
np.std(data, ddof=0)

**Take home message**: you should always take a look at NumPy's manual to make sure you are doing what you think you are doing -- keep an eye out for default settings (e.g. ddof=0).

---
### And finally, some weirdness

In [ ]:
import statistics

## Should provide a mean value of 1.0
np_mean = np.mean([1e30, 1, 3, -1e30])
statistics_mean = statistics.mean([1e30, 1, 3, -1e30])

print('Statistics mean: {}'.format(statistics_mean))
print('NumPy mean: {}'.format(np_mean))


From https://www.python.org/dev/peps/pep-0450/

"The built-in sum can lose accuracy when dealing with floats of wildly differing magnitude. Consequently, the above naive mean fails this "torture test"..."