# NumPy Random Numbers - Creating Toy Data

## Additional Information - Building upon the NumPy's Neural Network Lecture

<figure>
  <center>
    <img src="00_images/31_machine_learning/nn_perceptron_example_nodes.png" style="width: 500px; margin: 0 0px;"/><br>
    <img src="00_images/31_machine_learning/nn_perceptron_example.png" style="width: 1000px; margin: 0 0px;"/>
    <figcaption style="margin-top: 10px; color: black; font-style: italic;">
          <b>Figure 1</b>: Illustration of the NN that we will create (top). The NumPy details of this NN (bottom).<br>
    </figcaption>
  </center>
</figure>

A random **seed** will be **explicitly set**, allowing for **reproducible results** (i.e., for teaching purposes). The first epoch data generated below should correspond to the numeric values given in the figure above.

The object naming will also be done to parallel the figure above.

<font color='DodgerBlue'>**Random Number Generator** in NumPy</font>:
- `np.random.default_rng`: https://numpy.org/doc/stable/reference/random/generator.html
- Possible Number Distributions:
    - `numpy.random.Generator.normal`:
        - https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.normal.html
        - Generates a <font color='DodgerBlue'>**normal**</font> (Gaussian) distribution.
    - List of others: https://numpy.org/doc/stable/reference/random/generator.html#distributions


- `input_X1_np = rng.normal(size=(2, 10))`
    - `2`: **number** of <font color='dodgerblue'>**input**</font> data **samples** (e.g., 2 houses)
    - `10`: **number of features** (width) that describe each sample (e.g., number of rooms, size, etc.)

<br>

- `target_Y2_np = rng.normal(size=(2, 1))`
    - `2`: **number** of <font color='dodgerblue'>**output** data **samples**</font> (i.e., **every input sample needs an output**)
    - `1`: number of **predicted features** (width) (e.g., house price)

In [9]:
import numpy as np

In [10]:
def print_array_specs(in_arrays: dict):
    ''' Helper function for nicely printing NumPy and
        PyTorch arrays.

        Print: a) shape, b) data type, and
               c) values.
    '''
    for key, value in in_arrays.items():
        print(f'{key}:\n{value.shape}, {value.dtype}')
        print(f'{value}\n')

In [11]:
rng = np.random.default_rng(seed=12345)

input_X1_np = rng.normal(size=(2, 10))
target_Y2_np = rng.normal(size=(2, 1))

weight_W1_np = rng.normal(size=(10, 3))
weight_W2_np = rng.normal(size=(3, 1))

bias_B1_np = np.zeros(3)
bias_B2_np = np.zeros(1)

Examine the different NumPy arrays:
- **shapes** (important for matrix multiplication)
- data **types** (need to be same types)
- **values**

In [13]:
objects_ini = {'input_X1': input_X1_np, 'target_Y2': target_Y2_np,
               'weight_W1': weight_W1_np, 'weight_W2': weight_W2_np}

print_array_specs(in_arrays=objects_ini)

input_X1:
(2, 10), float64
[[-1.42382504  1.26372846 -0.87066174 -0.25917323 -0.07534331 -0.74088465
  -1.3677927   0.6488928   0.36105811 -1.95286306]
 [ 2.34740965  0.96849691 -0.75938718  0.90219827 -0.46695317 -0.06068952
   0.78884434 -1.25666813  0.57585751  1.39897899]]

target_Y2:
(2, 1), float64
[[ 1.32229806]
 [-0.29969852]]

weight_W1:
(10, 3), float64
[[ 0.90291934 -1.62158273 -0.15818926]
 [ 0.44948393 -1.34360107 -0.08168759]
 [ 1.72473993  2.61815943  0.77736134]
 [ 0.8286332  -0.95898831 -1.20938829]
 [-1.41229201  0.54154683  0.7519394 ]
 [-0.65876032 -1.22867499  0.25755777]
 [ 0.31290292 -0.13081169  1.26998312]
 [-0.09296246 -0.06615089 -1.10821447]
 [ 0.13595685  1.34707776  0.06114402]
 [ 0.0709146   0.43365454  0.27748366]]

weight_W2:
(3, 1), float64
[[0.53025239]
 [0.53672097]
 [0.61835001]]

